language: node_js
node_js: lts/carbon
services:
  - docker
addons:
  apt:
    packages:
    - libsecret-1-0
script:
  - chmod +x ./scripts/docker-deploy.sh
deploy:
  - provider: npm
    api_key:
      secure: qcjXLJme8UTBkn2tjYuOKIbBF2vuL50LQPuwKxpvj4/BKdiWzOssoVVUAU4uhMPiQaWl10W3cDsQ0PCQcXwf/PUWT5itNITRJjmL87/ayER9sDvs9U9p365w6fCykDDyAoGKAioRiVXXCyYsCikFR3NdzWj17yi+Bwwv0KIs/tAWusgqLFVPMpIzdCmqNIjw7v0T5FNIjrAILD6weF/ES7KcL6STrT610vxWXvhJnxPSJrQGcP3CPNrGw450PeR2Aiu4cOQu3G3arMYlGEm9fNbReV344N/cC2elgk4CbQTg+3Fn8yIXPWbKragqIenZ8zQLCOrgyY2ELTapq2TbmKL7eBurPEcYAyVwBG6+LzoToD3/BwY0ufT9kPUxttdVd6G4TnWYHs29b0DyW+bTSJmBiahByiKPIxwmsnl+q8eG0wmvGiR3uiLPONqZQoMml6b2mOQ9RXvWN8zJJKnLOZGtdg33CCmvvKif7ABEWzsvvtvG+9kjGt6ITW8tagwFSBMdj/ktXgMzQsrlzNX+FBf2IwmstSb6oUjariXrBDKS6cgs5ZBI2wi2SBehr+ssKWA2TF+tboJijx0FN8UZxj5O/L/zQe0/UHGBFn1V9T23mynUxVm4L5vhn1zvuD0C6+Y7Bb4YF6odXZpnrRd4Ivtb/SHb41lcOih8Iay5vtE=
    on:
      tags: true
      repo: pofallon/twine
    email:
      secure: K1diToHT1TX0JTvIbCVGGKQ+cAf7Qv0xk30KTNdbs7sK+u1tbRnjqSNIHoSGe3wdfbLmQplVkbe569n2Lbce1KKYOwWasIgu1jFa3Dy+elbhPkst7ioC/CF5tSPVnxKCtskclUnwHUYiZHriHNJGFsmq4hjaNRFVJ82cwnr11YZxLfz23/sBZuQFXOCtB5LS+Ldd0K3GcGoi/kgWOnBIAoCcfrluAzVZGKFsu+RQLrG8Njmw6Gn4kqtEo8bqP+RGRaj4TeXCALCZ+8cAJJPzA2Juvar1d8c52p2fS4QOPZFAEnhOxPXYEk6NznsCMP11+cQxBebQM36nugVRGzPfd6jBjfdtO2GrgONAl+4rEljNb0XGvynO9Qw3gsxxfs5iBLV+1pgEcqPJ2nRsRzQBEEJNLHeKhcUps4g79rLQS8yZHPb+Q/SfihpT75x3fYsbEuMlXZXla2kFccy1FU9HYeIJW84xSr8nhjl28QMfVJ5JYMTEgmplrsIw+ynAZ3Rnn/85YtMLIsdO4UZp6m20vIc62tkz5pNCXbF/35t3K+rVl4naiYl7wKi4PRBHW+wkBippFNxjiHaqmA7rraLkaesAzsnHTjkvS7kGRELAHQtEzKML0Y5slB1Pbr41xYwqEpTwh4YnYgPBC7QpNgONg1MF7Pa6UBUIpCmEKcj5BDQ=
  - provider: script
    script: bash ./scripts/docker-deploy.sh
    skip_cleanup: true
    on:
      tags: true
      repo: pofallon/twine
env:
  global:
  - secure: gXwOqWEnuD0LoXkRrtHTCx+GFNUb4NbKRndHPxDT85JSE8GiURAMReBxT+ibhilr/r98KcPz8shwJMzTWlMGadgG3fTECx8vDeLr2CuQv8YZ958680Y5ObYzjdiAD3sud2dV08+jTNhPBHZhe9WiCwFxgIGb8+Gn8Cv3yzwE3hgUr65kcxjRv5OdikXcK67qDfpzEfdCrlWmyyPDUG1qxfqxqA+mFT/tQ5WoWBoYfsnSy799fq835lKhyxI4dB1KsOfwNyPeVq3e1pUDcRgsuMXV7AH+jBfJae2uezCyfZtVtSDKUUx/kHbFYdZ19DjWIev++4w5wrP8+jEJ/sz2F4+cDpcn+QCp59WtgA5XaDJywujU1WpsxdZo8D10ywuK+zBgqCb7FTf0Q+78oq5na2XIabPNNDzOVuiK7pfSoKXdnr82mydW5eaPl79IX2xMFXHUyPMta6i4NLeNf2RcPWhtQRpfRinkLGJbL3EADxqrGs4xDZgeoGpX7AydawaygfG0hydN77IyAOQ6ziN9MISPnFOL/O5EgJRvr+TzTK6JtkXAgeUoO3IxdNOVhgfXCsfBBdVy1VhFFaanx2oTfHuxaNHTrs1HkFPfaR7SL5dYHPYSgZOYgZDjmWxBZuteGIQ4teEBHohATjVuAjYqVp239N9DCWZZzk42cCIYv9o=
  - secure: yimDtiKPDnYB3M2v/4zvX3Vs/zw5guugF+mUX1D/PO7xnC1F27FZViKonNsBT7XznykwUYbeIgB2ZvTXxTXt44PiLSfNaofScOthXL7BZSxQ8V3U8qAN6hUltqrJQ/3VfEMIW4tTVr9modP1fs/45sZj3baIymeUYBrUwNQbZMQ01KJVcXfgpavrUhNrga/CRKQIAV8qQGI5WkCOxTBzR3U+anzVG+0ywZ0pZ+iaUzrnuCjmM+/PJlWC4hB+GMqF4KZqDrMhpZemZY791Wx1H7NlrXAF/qwgPX5l5AvzaWc2U+G3mADlqWcQvzM0yL4zjPQU7uX+8XSsVcTJZe0M9Vs8G6ArdK54/pZ+sfGpigO7Qr057pBMB9WM/C0cem3u975IYmHfdkM9BbUArXbhtZQg/JIlmEEWOjH4uIsgk4O/lOmuKZEY9KgOMRYPTQgWg7atWKAD+KA7ehfJO1KhF+uOst0Cu55Q4LyOJrKTnLK2zviD2oE0+rB/YY+pPhqnCaAQJ3SXt4yAHsli8XyKMpGDONRt1N3mnhHi/c7i/bbU6KP2EYCOAxTEf3gLnjSIhby6GQ87Sx9/cHWLku7/15Zl8y9Th/0pMuh/E7jRprwvdI1MZGkVV6vZXnT2feBVvodasnKR7Zu/oUi9P/hF49iX1kzX86vjeWvDNnHhru8=
